keys:
  - &nixdesk age1uka040qsp84cq0vfw9usqgahcmn3gaenj9a66a8gw6vg5h928qys6tt7dq 
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *nixdesk

